---
- hosts: aws_ec2
  become: true
  gather_facts: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]

- hosts: webserver
  become: true
  gather_facts: false
  roles:
    - apache2
    - demo_app
