---
- name: install tools
  apt: name={{item}} state=present
  with_items:
    - python3-pymysql
  tags: [ 'packages' ]

- name: install mysql-server
  apt:
    name: mysql-server
    state: present
  tags: [ 'packages' ]


- name: ensure mysql listening on all ports
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: restart mysql
  tags: [ 'configure' ]

- name: ensure mysql started
  service:
    name: mysql
    state: started
    enabled: yes
  tags: [ 'service' ]

- name: create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [ 'configure' ]

- name: create demo user
  mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }} "
    priv: "{{ db_name }}.*:ALL"
    #priv: "{{ db_name }}.*:ALL"
    host: "{{ db_user_host }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  tags: [ 'configure' ]
